/**
 * Deterministic adapter-config generation. Turns a read-only ScanResult into a
 * draft `adapter.config.yaml`: every CTI capability becomes an operation
 * mapped to its best discovered endpoint (or flagged as a gap). No model
 * involved — this is the plain-code stage the LLM stages build on. Its output
 * is what stage 4 fills with mapping code and what `hippo conform` grades.
 */
import { TRADE_FEATURE_IDS } from '../scan/features.js'
import type { CapabilityId, ScanResult, VenueCapabilitiesShape } from '../scan/types.js'
import type { AdapterConfig, AdapterOperation } from './types.js'

/** Data-returning ops render into cards, so their venue shape needs a mapping
 * function. Pure actions (cancel) and event surfaces (webhooks) do not. */
const DATA_RETURNING: ReadonlySet<CapabilityId> = new Set([
  'quote',
  'orderPlacement',
  'orderStatus',
  'positions',
  'balances',
  'instruments',
])

/** Infer a signing strategy from the declared auth schemes. */
function authStrategy(schemes: string[]): string {
  const blob = schemes.join(' ').toLowerCase()
  if (/hmac|signature|sign/.test(blob))
    return 'hmac-signed request (per-key secret; see the Assetworks adapter as the reference pattern)'
  if (/bearer|oauth|jwt/.test(blob)) return 'bearer token'
  if (/apikey|api-key|x-.*key/.test(blob)) return 'api-key header'
  return 'unknown — confirm with the venue before implementing'
}

/** Origin of the discovered site, the least-wrong default for the API base. */
function baseUrlGuess(scan: ScanResult): string | null {
  const src = scan.spec?.url ?? scan.site.finalUrl
  try {
    return new URL(src).origin
  } catch {
    return null
  }
}

export function draftAdapterConfig(scan: ScanResult): AdapterConfig {
  const operations: AdapterOperation[] = scan.capabilities.map((cap) => {
    const [endpoint, ...alternates] = cap.endpoints
    const mapped = cap.status === 'found' && typeof endpoint === 'string'
    return {
      capability: cap.id,
      label: cap.label,
      status: mapped ? 'mapped' : 'gap',
      endpoint: mapped ? endpoint : null,
      alternates: mapped ? alternates.filter((a) => !a.startsWith('…')) : [],
      needsMappingCode: mapped && DATA_RETURNING.has(cap.id),
      note: mapped ? 'confirm request/response shape against the CTI' : cap.consequence,
    }
  })

  return {
    venue: scan.domain,
    baseUrl: baseUrlGuess(scan),
    auth: { schemes: scan.authSchemes, strategy: authStrategy(scan.authSchemes) },
    tradeFeatures: scan.tradeFeatures ?? null,
    operations,
    gaps: operations.filter((o) => o.status === 'gap').map((o) => o.capability),
    needsMappingCode: operations.filter((o) => o.needsMappingCode).map((o) => o.capability),
  }
}

// ── YAML rendering ────────────────────────────────────────────────────────
// Hand-rolled for this known-shaped document — no YAML dependency. Values that
// can contain spaces or slashes (endpoints, notes) are double-quoted.

const q = (s: string): string => `"${s.replace(/"/g, '\\"')}"`

export function renderAdapterConfigYaml(config: AdapterConfig): string {
  const lines: string[] = []
  const push = (...ls: string[]) => lines.push(...ls)

  push(
    `# Hippo adapter config (draft) — ${config.venue}`,
    '# Generated by `hippo init` from a read-only scan. Declarative-first:',
    '# this file maps CTI operations to venue endpoints. A "gap" needs venue',
    '# input; needsMappingCode ops get a mapping.ts function (stage 4). The',
    '# generated adapter must pass `hippo conform` before it ships.',
    '',
    `venue: ${q(config.venue)}`,
    `baseUrl: ${config.baseUrl ? q(config.baseUrl) : '"TODO: confirm the API base URL"'}`,
    'auth:',
    '  schemes:',
  )
  if (config.auth.schemes.length === 0) push('    [] # none declared in the spec')
  else for (const s of config.auth.schemes) push(`    - ${q(s)}`)
  push(`  strategy: ${q(config.auth.strategy)}`)

  if (config.tradeFeatures) {
    pushCapabilitiesBlock(push, config.tradeFeatures)
  }

  push('', 'operations:')

  for (const op of config.operations) {
    push(`  ${op.capability}:`, `    status: ${op.status}`)
    if (op.status === 'mapped') {
      push(`    endpoint: ${q(op.endpoint ?? '')}`)
      if (op.alternates.length > 0) {
        push('    alternates:')
        for (const a of op.alternates) push(`      - ${q(a)}`)
      }
      if (op.needsMappingCode) push('    needsMappingCode: true')
    } else {
      push(`    note: ${q(op.note)}`)
    }
  }

  push('')
  push('gaps:')
  if (config.gaps.length === 0) push('  [] # every CTI capability mapped')
  else for (const g of config.gaps) push(`  - ${g}`)

  push('')
  return lines.join('\n')
}

/**
 * The `capabilities:` block — the trade-type feature set the generated adapter
 * must implement (protocol VenueCapabilities semantics). Detection is a
 * keyword candidate, not proof: incomplete params are flagged, never invented.
 */
function pushCapabilitiesBlock(
  push: (...ls: string[]) => void,
  features: VenueCapabilitiesShape,
): void {
  push(
    '',
    '# Trade-type feature set detected from the public spec (candidates, not proof).',
    '# Enabled features are what the generated adapter must implement; params are',
    '# what the capability modules validate against (protocol VenueCapabilities).',
    'capabilities:',
  )
  for (const id of TRADE_FEATURE_IDS) {
    const feature = features[id]
    if (!feature) {
      push(`  ${id}:`, '    enabled: false # not detected in the public API surface')
      continue
    }
    push(`  ${id}:`, '    enabled: true')
    if ('maxLeverage' in feature && feature.maxLeverage !== undefined) {
      push(`    maxLeverage: ${feature.maxLeverage}`)
    }
    if ('marginModes' in feature && feature.marginModes && feature.marginModes.length > 0) {
      push('    marginModes:')
      for (const mode of feature.marginModes) push(`      - ${mode}`)
    }
    if (feature.paramsIncomplete) {
      push(
        '    paramsIncomplete: true # heuristic candidate — confirm validation params with the venue',
      )
    }
  }
}
